name: Laravel Tailadmin CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: pratama2009-tailadmin-laravel:beta

jobs:

  run-mysql:
    runs-on: self-hosted
    steps:
      - name: Clean old containers
        run: docker ps -aq | xargs -r docker rm -f || true

      - name: Run MySQL
        run: |
          docker run -d \
          --name mysql \
          -e MYSQL_ROOT_PASSWORD=password \
          -e MYSQL_DATABASE=laravel \
          -p 3306:3306 \
          mysql:5.7

      - name: Check containers
        run: docker ps -a

  build-image:
    needs: run-mysql
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: List images
        run: docker images

  deploy:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old container (if exists)
        run: docker rm -f tailadmin-web || true

      - name: Run new container
        run: |
          docker run -d \
          --name tailadmin-web \
          -p 8090:80 \
          $IMAGE_NAME

      - name: Show running containers
        run: docker ps -a
